### PR TITLE
Everything uses event_instances now instead of events

### PR DESCRIPTION
**Pull request by LuxBetancourt**
Also some minor fixes to things

### CODE REVIEW

**Comment by mingyanw** [comment]
Testing Notes: 
-Able to add static events to the system - adding dynamic events (with no dates or time specified) fails with no notification
-In Calendar view, when the user clicks on READ MORE, it links to the event_instance JSON file instead of the show_event view:
screenshot 2015-10-15 11 53 30
-Agenda view links to the event is not linked properly (links to event with the event_instance id) 
screenshot 2015-10-15 11 55 09

**Comment by mingyanw** [comment]
@Lankly I can merge this after you confirm the testing notes above & assign owners to the issue fixes!

**Comment by mingyanw** [comment]
@Lankly I just merged @GSchill25 's pull request so there might be merge conflicts - please do a pull, resolve the conflicts, and push again when you have time. Thanks! :cactus:

**Comment by LuxBetancourt** [comment]
How's this?

**Comment by mingyanw** [comment]
Testing Notes:

Agenda View and Calendar View are restored to being able to handle static events (events where users input date, time, and duration).
screenshot 2015-10-20 14 56 15

Something seems broken with the Past Event partial on certain pages - Dashboard also not working as expected, as shown below :sob: 
screenshot 2015-10-20 14 56 29

**Comment by LuxBetancourt** [comment]
I think I've got it now.

**Comment by mingyanw** [comment]
Closing this for now - can re-open in the future if anyone wants to extend the system functionality!

**Pull request closed without merging**
